service:
  name: crwn-clothing-website

provider:
  name: aws

plugins:
  - serverless-s3-deploy

custom:
  assets:
    auto: true
    targets:
      - bucket:
          Ref: CrwnClothingWebsiteBucket
        acl: public-read
        files:
          - source: 'build/'
            globs: ['**/*']
            headers:
              CacheControl: max-age=31536000

resources:
  Resources:
    CrwnClothingWebsiteBucket:
      ${file(deploy/templates/s3.yml):S3Bucket}

  Outputs:
    WebsiteBucketName:
      Value:
        !GetAtt CrwnClothingWebsiteBucket.Arn
    WebsiteBucketDomainName:
      Value:
        !GetAtt CrwnClothingWebsiteBucket.DomainName
    WebsiteBucketWebsiteUrl:
      Value:
        !GetAtt CrwnClothingWebsiteBucket.WebsiteURL

